//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langate.FacialRecognition.Mobile.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Langate.FacialRecognition.Mobile.Resources.Strings.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At:.
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm accuracy of
        ///your data and photos.
        /// </summary>
        internal static string ConfirmAccuracy {
            get {
                return ResourceManager.GetString("ConfirmAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue verification for:.
        /// </summary>
        internal static string ContinueSubmissionTo {
            get {
                return ResourceManager.GetString("ContinueSubmissionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending invites:.
        /// </summary>
        internal static string ContinueWith {
            get {
                return ResourceManager.GetString("ContinueWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A discrepancy exists between your entered personal data and that read from your ID by the system.  Please review your entries as any discrepancy requires manual review and may delay your verification..
        /// </summary>
        internal static string DiscrepancyIsFound {
            get {
                return ResourceManager.GetString("DiscrepancyIsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User Agreement.
        /// </summary>
        internal static string EndUserAgreement {
            get {
                return ResourceManager.GetString("EndUserAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure all words and numbers are clear and readable. If not, please retake as it will delay the verification process and your ability to progress with this study’s screening..
        /// </summary>
        internal static string EnsureAllWorldsClear {
            get {
                return ResourceManager.GetString("EnsureAllWorldsClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Personal Data.
        /// </summary>
        internal static string EnterPersonalData {
            get {
                return ResourceManager.GetString("EnterPersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCT has detected a possible protocol violation. This information is being shared with the research site and applicable study staff..
        /// </summary>
        internal static string ErrorPassedVerificationDescription {
            get {
                return ResourceManager.GetString("ErrorPassedVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCT has detected a possible protocol violation.
        /// </summary>
        internal static string ErrorUploading {
            get {
                return ResourceManager.GetString("ErrorUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact VCT or your research site for more information..
        /// </summary>
        internal static string ErrorUploadingBottomText {
            get {
                return ResourceManager.GetString("ErrorUploadingBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exactly as it appears on the valid ID you will be using for this verification.
        /// </summary>
        internal static string ExectlyAsIt {
            get {
                return ResourceManager.GetString("ExectlyAsIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 3 letters of your first name.
        /// </summary>
        internal static string FirstThreeLettersFirstName {
            get {
                return ResourceManager.GetString("FirstThreeLettersFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 3 letters of your last name.
        /// </summary>
        internal static string FirstThreeLettersLastName {
            get {
                return ResourceManager.GetString("FirstThreeLettersLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no middle initial enter a dash.
        /// </summary>
        internal static string IfNoMiddleInitial {
            get {
                return ResourceManager.GetString("IfNoMiddleInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have multiple last names enter the first 3 letters of your first last name. If your last name is only 2 digits enter a dash as the third character.
        /// </summary>
        internal static string IfYouHaveMultipleNames {
            get {
                return ResourceManager.GetString("IfYouHaveMultipleNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (last 5 characters).
        /// </summary>
        internal static string LastDigits {
            get {
                return ResourceManager.GetString("LastDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle initial.
        /// </summary>
        internal static string MiddleInitial {
            get {
                return ResourceManager.GetString("MiddleInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake  .
        /// </summary>
        internal static string Retake {
            get {
                return ResourceManager.GetString("Retake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Your Photo.
        /// </summary>
        internal static string ReviewYourPhoto {
            get {
                return ResourceManager.GetString("ReviewYourPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using VCT Virtual App! Good luck in this study and stay safe..
        /// </summary>
        internal static string StandaloneText {
            get {
                return ResourceManager.GetString("StandaloneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start verification for:.
        /// </summary>
        internal static string StartSubmissionTo {
            get {
                return ResourceManager.GetString("StartSubmissionTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Verification.
        /// </summary>
        internal static string StudyVerification {
            get {
                return ResourceManager.GetString("StudyVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations! You have successfully passed the verification process. Please use the link below to continue with your screening visit..
        /// </summary>
        internal static string SuccessfullyPassedVerificationDescription {
            get {
                return ResourceManager.GetString("SuccessfullyPassedVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully passed verification.
        /// </summary>
        internal static string SuccessfulUploading {
            get {
                return ResourceManager.GetString("SuccessfulUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture looking straight in to the camera.
        /// </summary>
        internal static string TakeFrontalPhotoText {
            get {
                return ResourceManager.GetString("TakeFrontalPhotoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take a picture looking 
        ///straight in to the camera.
        /// </summary>
        internal static string TakeFrontPhoto {
            get {
                return ResourceManager.GetString("TakeFrontPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold the camera in your right
        ///hand and take a picture of
        ///the right side of your face.
        /// </summary>
        internal static string TakeLeftPhoto {
            get {
                return ResourceManager.GetString("TakeLeftPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take photo of your valid ID.
        /// </summary>
        internal static string TakePhotoId {
            get {
                return ResourceManager.GetString("TakePhotoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold the camera in your left
        ///hand and take a picture of
        ///the left side of your face.
        /// </summary>
        internal static string TakeRightPhoto {
            get {
                return ResourceManager.GetString("TakeRightPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of ID.
        /// </summary>
        internal static string TypesOfId {
            get {
                return ResourceManager.GetString("TypesOfId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading images.
        /// </summary>
        internal static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid ID.
        /// </summary>
        internal static string ValidId {
            get {
                return ResourceManager.GetString("ValidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information provided does not match and requires review. Please contact VCT or your research site for more information..
        /// </summary>
        internal static string WarningLastPassedVerificationDescription {
            get {
                return ResourceManager.GetString("WarningLastPassedVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information provided does not match and requires review..
        /// </summary>
        internal static string WarningLastUploading {
            get {
                return ResourceManager.GetString("WarningLastUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact VCT or your research site for more information..
        /// </summary>
        internal static string WarningLastUploadingBottomText {
            get {
                return ResourceManager.GetString("WarningLastUploadingBottomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your facial photos were not captured correctly. Please try again or call
        ///516 998 7499 with questions..
        /// </summary>
        internal static string WarningPassedVerificationDescription {
            get {
                return ResourceManager.GetString("WarningPassedVerificationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your facial photos were not captured correctly.
        /// </summary>
        internal static string WarningUploading {
            get {
                return ResourceManager.GetString("WarningUploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at:.
        /// </summary>
        internal static string WelcomeAt {
            get {
                return ResourceManager.GetString("WelcomeAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to verify yourself by Dr..
        /// </summary>
        internal static string WelcomeName {
            get {
                return ResourceManager.GetString("WelcomeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your subject number is:.
        /// </summary>
        internal static string WelcomeNumber {
            get {
                return ResourceManager.GetString("WelcomeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to .
        /// </summary>
        internal static string WelcomeTo {
            get {
                return ResourceManager.GetString("WelcomeTo", resourceCulture);
            }
        }
    }
}
